require 'json'
require 'thor'
require 'httparty'
require 'geocoder'
require 'rainbow'

require_relative 'hawk/version'
require_relative 'hawk/geocoder_service'
require_relative 'hawk/overpass_service'
require_relative 'hawk/elevation_service'
require_relative 'hawk/weather_service'
require_relative 'hawk/profiler'
require_relative 'hawk/report'
require_relative 'hawk/cli'